### ISSUE TITLE
Use with coupon codes

### ISSUE THREAD

**Issue by sleepigrl** [witrin/magento-gifts#11]
I'm not entirely sure from the documentation & notes whether this extension should work with coupon codes. 

If it should be working, it doesn't calculate correctly.  When the shopper is over the purchasing level for a free gift AND uses a coupon code, the cost of the gift is added to their cart (and then discounted based on the coupon).

For example, we have a rule that gives a free gift when the customer purchases over 
$50 in merchandise.

-- With no coupon code - free gift is added to cart (great!)
-- With a 10% off coupon code - cost of "free gift" is added to the cart.  Subtotal including cost of "free gift" is discounted 10%.  (uh oh!)

Desired result for the above transaction:
-- Free gift added to cart
-- Remaining items in the cart are discounted 10%

**Comment by witrin** [comment]
In this case I would say it should work with it! Unfortunately, latest in a month I can begin troubleshooting. I hope this is okay for you.

**Comment by sleepigrl** [comment]
Good to know it's not just me.  Of course, I'd prefer it to be fixed yesterday (shouldn't everything be done that way?), but I understand time constraints :)

Thanks for the quick response and I'll keep an eye so that I know when you've updated.

**Comment by sleepigrl** [comment]
After further review, I've discovered that this DOES work when a coupon is used.  My client's math was faulty :)

But it would be nice to have the option to turn the gift off if a coupon is used.

**Comment by witrin** [comment]
In this case it is a feature request, please create a new one.
