### ISSUE TITLE
Fatal error: Class 'Mage_Rule_Model_Abstract' not found

### ISSUE THREAD

**Issue by ethicapress** [witrin/magento-gifts#12]
Hello,

I installed your extension on Magento CE 1.6.2 and even though I cleared all the caches, logged out and in again, I get this error in the configuration page (Promotions -> Shopping Cart Gift Rules): 

Fatal error: Class 'Mage_Rule_Model_Abstract' not found in /home/xxx/public_html/app/code/community/Ionoi/Gift/Model/Rule.php on line 13.

Please take a look at this issue.

Thank you!

Marius C.

**Comment by witrin** [comment]
Please check the prerequisites. Magento CE 1.6.2 is unfortunately not supported.
