### ISSUE TITLE
Unable to add Gift Product

### ISSUE THREAD

**Issue by adeelkalyami** [witrin/magento-gifts#13]
Hi, 
Thanks for developing such a nice extension, but i am not finding it useful. I have installed extension on Magento 1.7, Installation was successfull, created gift rule from backend, but i am unable to see anything on frontend of site.

![frontend](https://f.cloud.github.com/assets/4425511/907102/aaa30222-fd0b-11e2-9621-bc9a7fbc0bf7.png)
![backend](https://f.cloud.github.com/assets/4425511/907103/aaaa315a-fd0b-11e2-9513-bb44d1d519bd.png)

Will be thankful for your quick response.

**Comment by witrin** [comment]
Please make a full screenshot of all other tabs.

**Comment by adeelkalyami** [comment]
Hi, 
Thanks for your response.
Apology from my side, actually my template is having some issue that is why i am unable to add gift product. I have tested it, it is working fine in default theme. 

(10/10) for your extension :)

You can now close the issue.
