### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EVOW** [witrin/magento-gifts#16]
i installed the extention, deleted the cache, but when i go to promotions- shopping gift card rules i get an error:

 Fatal error: Class 'Mage_Rule_Model_Abstract' not found in /home/sextoys/public_html/app/code/community/Ionoi/Gift/Model/Rule.php on line 12

i use magento 1.4.2.0

What is the problem?

**Comment by witrin** [comment]
The minimum required version of Magento is 1.7.
