### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EVOW** [witrin/magento-gifts#17]
i installed with connect but getting an error

There has been an error processing your request

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sextoysn_magento.gift_rule' doesn't exist

magento version 1.7.0.2

**Comment by witrin** [comment]
I guess you installed the extension before you upgrade to Magento 1.7. Try to execute this SQL statement `delete from core_resource where code = 'gift_setup';`.

**Comment by EVOW** [comment]
no
this was a webshop with 1.7.0.2. allready installed before installing the extention.

**Comment by witrin** [comment]
Well for some reason I don't know, the setup script was not executed. So try it with the SQL statement and clear all caches.

**Comment by EVOW** [comment]
ok i did what you say, now i can access the extention settings page.

but when i want to add a product it cant find any products

**Comment by witrin** [comment]
You have to filter for products in the list.

**Comment by EVOW** [comment]
i try to search for a product that exists, but nothing is found

**Comment by EVOW** [comment]
got it. had to reset filter

**Comment by witrin** [comment]
Please make sure you set all filters right, especially the first one. This is a standard Magento view.
