### ISSUE TITLE
Free Gift only displays after refresh and backend doesn't show free product on order

### ISSUE THREAD

**Issue by picturekeeper** [witrin/magento-gifts#18]
We installed your Gift extension and need some advice.  I’ve attached two screen shots to show you how we configured a Rule.  We’re trying to offer a Free gift (ie product 110 called “4GB Stocking Stuffer $30 Value") for each cart with one of two conditions.  First condition is atleast quantity 2 of our PK4 product and second condition is any of the following sku’s ( 8gbpkbx, 16gbpkbx, 32gbpkbx, pkpro320, 2x8gbpk, pkpro).

This rule is live on our site at picturekeeper.com.  There are two issues. 

Issue 1 : we would like to see the free gift displayed in the cart but it only appears after a manual refresh of the page. 

Issue 2:  We see the free gift added only at the order summary at check out but when we check the order details via the admin panel at picturekeeper.com/admin the gift is not included in the order.

Can you offer any advice?  I can provide login credentials to picturekeeeper.com/admin if needed.

Note: We are running magento CE 1.7.0.2.

Thank you,

Matt Stanchie
![gift2](https://f.cloud.github.com/assets/5930851/1532749/50ec7ec4-4c7b-11e3-92a6-520461bcc9d8.png)
![gift](https://f.cloud.github.com/assets/5930851/1532750/50ed1046-4c7b-11e3-9799-7c1dc7f39f18.png)

**Comment by witrin** [comment]
Thank you very much for your bug report! Unfortunately currently I'm under heavy time pressure. This means maybe I'll find the time tomorrow to check your report. But I'm pretty sure not able to fix this before end of december.

**Comment by witrin** [comment]
Sorry but I can't reproduce your reported bug. I've tested your sample with on a clean setup (CE 1.7.0.2). Have I missed something? What extensions have you installed?
![1](https://f.cloud.github.com/assets/1394346/1541242/e3416396-4d31-11e3-9bac-99bc5fff5044.png)
![2](https://f.cloud.github.com/assets/1394346/1541244/e9d48b34-4d31-11e3-826d-8f901779208e.png)
![3](https://f.cloud.github.com/assets/1394346/1541247/ec67b358-4d31-11e3-9c5a-b57c9193c618.png)
![4](https://f.cloud.github.com/assets/1394346/1541249/f091c5ea-4d31-11e3-9117-97769629575d.png)

**Comment by picturekeeper** [comment]
Thank you for your quick response.  By they way _strangely_ the gift does show up in maybe in 1 out of 10 orders.  

Here are the extensions we've installed over the years:

Adroll_Liquidads.xml                    Mage_Api.xml
Amasty_Base.xml                         Mage_Authorizenet.xml
Amasty_Coupons.xml                      Mageb2bextensions_LoginCatalog.xml
Amasty_Methods.xml                      Mage_Bundle.xml
Amasty_Orderattach.xml                  Mage_Captcha.xml
Amasty_Xcoupon.xml                      Mage_Centinel.xml
Aschroder_Email.xml                     Mage_Compiler.xml
Aschroder_SMTPPro.xml.replaced          Mage_Connect.xml
AW_All.xml                              Mage_CurrencySymbol.xml
AW_Mobile.xml                           Mage_Downloadable.xml
AW_Rma.xml                              Mage_GoogleTrustedStore.xml
Biebersdorf_CustomerOrderComment.xml    Mage_ImportExport.xml
BusinessDecision_Interaktingslider.xml  MagentoPycho_Lightboxes.xml
Daft_Locations.xml                      Mage_Oauth.xml
EcomDev_ConnectAffiliate.xml            Mage_PageCache.xml
EcomDev_PhoneForOrderGrid.xml           Mage_Pap.xml
EcomDev_ProductCustomer.xml             Mage_Persistent.xml
Find_Feed.xml                           Mage_Weee.xml
German_LocalePackDe.xml                 Mage_Widget.xml
HusseyCoding_Common.xml                 Mage_XmlConnect.xml
HusseyCoding_CustomOrderGrid.xml        Mmsmods_Serialcodes.xml
Idev_OneStepCheckout.xml                News_Slideshow.xml
IG_FlatShipping5.xml                    Phoenix_Moneybookers.xml
Intersec_Orderimportexport.xml          Phoenix_VarnishCache.xml
Ionoi_Gift.xml                          Picturekeeper_Customer.xml
Magalter_Config.xml                     Picturekeeper_Reviews.xml
Magalter_Upsells.xml                    QS_Addressvalidation.xml
Mage_All.xml                            Shipwire_Shipping.xml
Mage_AmazonPayments.xml                 Turnkeye_Testimonial.xml
Mage_Api2.xml                           Yireo_DeleteAnyOrder.xml

**Comment by witrin** [comment]
I would guess that there is an incompatibility at least with one of these extensions. So you have to test which before I can help.

**Comment by stason78** [comment]
@picturekeeper Did you find out what caused this issue? I'm having the exact same problem.

**Comment by witrin** [comment]
@stason78 Maybe you could check which non-core extensions you have in common with picturekeeper...

**Comment by picturekeeper** [comment]
We're still trying to resolve this issue.  It's strange because some orders do contain the free gift and some do not.  There is no pattern.

Here's a better sorted list of our extensions:

Mage_Api.xml
Mage_Authorizenet.xml
Mage_Bundle.xml
Mage_Captcha.xml
Mage_Centinel.xml
Mage_Connect.xml
Mage_CurrencySymbol.xml
Mage_Downloadable.xml
Mage_GoogleTrustedStore.xml
Mage_PageCache.xml
Mage_Widget.xml
Mage_Oauth.xml
Mage_ImportExport.xml
Mage_Compiler.xml
Mage_Weee.xml

Adroll_Liquidads.xml 
Amasty_Base.xml 
Amasty_Coupons.xml 
Mageb2bextensions_LoginCatalog.xml
Amasty_Methods.xml 
Amasty_Orderattach.xml 
Amasty_Xcoupon.xml 
Aschroder_Email.xml 
Aschroder_SMTPPro.xml.replaced 
AW_All.xml 
AW_Mobile.xml 
AW_Rma.xml 
Biebersdorf_CustomerOrderComment.xml 
BusinessDecision_Interaktingslider.xml 
MagentoPycho_Lightboxes.xml
Daft_Locations.xml 
EcomDev_ConnectAffiliate.xml 
EcomDev_PhoneForOrderGrid.xml
Mage_Pap.xml
EcomDev_ProductCustomer.xml 
Mage_Persistent.xml
Find_Feed.xml 
German_LocalePackDe.xml 
HusseyCoding_Common.xml Mage_XmlConnect.xml
HusseyCoding_CustomOrderGrid.xml 
Mmsmods_Serialcodes.xml
Idev_OneStepCheckout.xml 
News_Slideshow.xml
IG_FlatShipping5.xml 
Phoenix_Moneybookers.xml
Intersec_Orderimportexport.xml 
Phoenix_VarnishCache.xml
Ionoi_Gift.xml 
Picturekeeper_Customer.xml
Magalter_Config.xml 
Picturekeeper_Reviews.xml
Magalter_Upsells.xml 
QS_Addressvalidation.xml
Shipwire_Shipping.xml
Turnkeye_Testimonial.xml
Yireo_DeleteAnyOrder.xml

**Comment by stason78** [comment]
Here are the ones we both have in common:

Mage_Api
Mage_Authorizenet
Mage_Bundle
Mage_Captcha
Mage_Centinel
Mage_Connect
Mage_CurrencySymbol
Mage_Downloadable
Mage_PageCache
Mage_Widget
Mage_Oauth
Mage_ImportExport
Mage_Weee
Idev_OneStepCheckout
Ionoi_Gift
Phoenix_Moneybookers

I hope it isn't caused by the OnestepCheckout...

**Comment by picturekeeper** [comment]
I know what you mean....most extensions don't work well with OSC.  We're looking into it still and should have a resolution in a couple of days.  I'll email support@OSC too.

**Comment by witrin** [comment]
I'm pretty sure that `Idev_OneStepCheckout` causes the problem, because all extensions prefixed with `Mage_` are part of the core just as `Phoenix_Moneybookers`. So try it by disabling it and we'll see...

**Comment by stason78** [comment]
Damn... I tried the OnePage checkout instead and it worked fine. Workaround for this...? pretty please :)

**Comment by witrin** [comment]
Sorry but I'm not willing to debug problems with a charged extension ;). But the company of this extension is welcome to contribute. Hope you'll understand this...

**Comment by stason78** [comment]
Understandable! I will contact them aswell.

**Comment by stason78** [comment]
@picturekeeper Anton at OneStepCheckout helped me sort out the problem! Comment out this code in app/code/local/Idev/OneStepCheckout/Block/Checkout.php and it will work: $this->getOnepage()->getQuote()->setTotalsCollectedFlag(false)->collectTotals();

@witrin Thanks again for the awsome plugin.

**Comment by witrin** [comment]
Glad to hear it.

**Comment by witrin** [comment]
I guess the problem is thereby closed.
