### ISSUE TITLE
is possible to show gift product link in product overview page?

### ISSUE THREAD

**Issue by muralidharan118** [witrin/magento-gifts#19]
i want to give one gift(product_gift_y) to product X, i want to show gift(product_gift_y)  link in particular(product X) overview page.

**Comment by witrin** [comment]
What you want is easy done with layout updates and a custom block. Your custom block should be able to output a gift (y) by its product id, which is set by layout updates of a product (x). The block itself can be also placed into the product view by layout updates, either by the product or by your theme.
