### ISSUE TITLE
Admin disappears after installing Gift Rules

### ISSUE THREAD

**Issue by Sajttim** [witrin/magento-gifts#20]
Hi,

I have a weird new problem which I have never had before with Magento. I am currently using 1.7.0.2

When I install an extension through Magento Connect (This part of the process works fine and it reports installation was successful etc) and I return to admin all I get on the admin side is a blank page with the header.

It did not affect the frontend and the shop itself seem unaffected ..

It was just the admin section that disappeared (Except for the header)

![adminerror](https://f.cloud.github.com/assets/6008327/1599160/46982f52-534e-11e3-8206-d230bc9a9213.jpg)

When I delete or rename /app/code/community/Ionoi folder, then admin section is working fine.

Please help or advice...

Thanks!

**Comment by witrin** [comment]
Try to clear the cache. Maybe you also had enabled the compiler, disable it before installing.

**Comment by Sajttim** [comment]
Thank you. I have compailer enabled, if I put it to disable, everything working fine.
