### ISSUE TITLE
Gift not enable

### ISSUE THREAD

**Issue by mickaellgr** [witrin/magento-gifts#21]
Hi,

The present is not visible in the basket. I am on Magento 1.7.0.2...

Can you help me please?

Thank you

![1](https://f.cloud.github.com/assets/6104167/1672582/6b5e80da-5cd5-11e3-9344-352289058313.jpg)
![2](https://f.cloud.github.com/assets/6104167/1672612/c5333a38-5cd5-11e3-981f-2874a811af93.jpg)
![3](https://f.cloud.github.com/assets/6104167/1672613/c533defc-5cd5-11e3-85a7-820531b29714.jpg)

**Comment by witrin** [comment]
Please upload your screenshots in english! Have you tried it with the default frontend design?

**Comment by witrin** [comment]
Ticket closed due to longer inactivity.
