### ISSUE TITLE
Order from backend fails

### ISSUE THREAD

**Issue by onepack** [witrin/magento-gifts#27]
When you try to create an order from the Magento backend and the gift conditions are met it will always fail with the message "The configured gift could not be found."

**Comment by witrin** [comment]
Sorry, I've never mentioned this case. I think this requires other event handler. Unfortunately, currently I'm not able to fix this due to time problems.

**Comment by onepack** [comment]
I thought so ;) I will look into it but not sure where to start yet.

**Comment by onepack** [comment]
I have not been able to fix this until now. This module is great but cannot be used in live stores as it makes it impossible to create backend-admin orders that meet the conditions set to receive the gift.

**Comment by onepack** [comment]
In Validator.php I changed:
`if (!$product || !$product->getId() ||
             !is_array($product->getWebsiteIds()) ||
             !in_array(Mage::app()->getStore()->getWebsiteId(), $product->getWebsiteIds())) {
                if (Mage::app()->getStore()->isAdmin()) {
                    return $product;
                }
            Mage::throwException(Mage::helper('gift')->__('The configured gift could not be found.'));
             }
        return $product;
    }`

It works now in the Admin Orders as well.
It might not be the best solution but it works fine until now.

**Comment by witrin** [comment]
Does it now behaves like you would expect?

**Comment by witrin** [comment]
I guess the gift is missing in the backend right?

**Comment by onepack** [comment]
Yeah, all seems to work fine :+1: 
Even the Gift product gets added to the order in the backend.
Until now I haven't found any unexpected behavior.
What do you think? Permanent solution?

**Comment by witrin** [comment]
In this case I would recommend a pull request.

**Comment by onepack** [comment]
Done. I hope you can use it.

**Comment by witrin** [comment]
Thanks! I'll will merge it within the next days.

**Comment by onepack** [comment]
Resolved. Can be closed.
