### ISSUE TITLE
Gift rules are processed twice

### ISSUE THREAD

**Issue by phainopepla** [witrin/magento-gifts#9]
Gifting `1` product for free based on purchase of `2` other products in specified categories causes `2` gifts to be added to the cart instead of one. If I set the free quantity to `3`, then it adds `6` gifts. In other words, it always doubles the gifts. It looks as if it is processing twice.

**Comment by witrin** [comment]
I'll see to it next week. Thanks for your contribution!

**Comment by phainopepla** [comment]
Thanks!

**Comment by witrin** [comment]
I'll fix this with the next patch release 1.0.2.

**Comment by witrin** [comment]
@phainopepla Could you please test the latest development release? Just use the [download](https://github.com/witrin/magento-gifts/archive/development.zip), copy the `app` folder into your Magento root directory and clear the Magento caches.

**Comment by phainopepla** [comment]
Seems to be working great Thanks!
